### ISSUE TITLE
Hot-Swap Userspace Kernel

### ISSUE THREAD

**Issue by DronCode** [DronCode/core2#2]
Нужен механизм горячей замены кода клиента. 
При это с корректной отгрузкой состояния виртуальной машины и обратной инициализацией. 
Думаю приемлимым вариантом будет схема: 
main - загружает -> Attach kernel.so - загружает -> Attach app.so 

и дальше если есть сигнал на обновление, то kernel.so запускает app.so::unload(), а уже внутри будет сохранение состояния вирутальной машины без потери сокета. Т.к. управление сокетами все равно идет в kernel.so, то потерь не будет.

**Comment by DronCode** [comment]
Если вообще брать такую тему, то архитектура библиотеки меняется, но не сильно

**Comment by DronCode** [comment]
Ну и в качестве базового наброска нужно будет тогда из userspace.so экспортировать парочку ф-ий:
* int ker_init() <- базовая инициализация
* int ker_save() <- требование сохранить свое состояние (не обязательно будет удаление, всякое бывает)
* int ker_unload() <- требование освободить все свои ресурсы, сохранить состояния, если это не было сделано и готовиться к концу
* int ker_get_revision() <- получить текущую ревизию библиотеки, для того, чтобы в логе можно было определить мы вообще обновились или как

**Comment by DronCode** [comment]
И надо бы при помощи volatile экспортировать бинарную сигнатуру для проверки целевой совместимости перед тем, как освобождать ресурсы.

**Comment by DronCode** [comment]
Сошелся примерно к такому 
```
volatile const unsigned char kernelSpaceTitle[4] = { 0x1B, 0xF2, 0xEE, 0xFF };
volatile const unsigned char kernelSpace[4]      = { 0xDE, 0xAD, 0xBE, 0xEF };
```

Дальше задача сводится к поиску заголовка и поиску сигнатуры, что в целом не шибко сложно

**Comment by DronCode** [comment]
Так, в коммите 3add4dcda265262e4aef951016a2782a7a5c2b86 есть первичный драфт. 
Надо протестить!
- [ ] Проверить первичный драфт AppSpace

**Comment by DronCode** [comment]
Создал тестовый проект и попробовал прогнать инициализацию. 

Полученные проблемы:
 
1) Косячное условие
`if (fPtr != nullptr) {`

2) UB в AppSpace::loadSpace когда все условия выполнены

Исправлено в ветке

**Comment by DronCode** [comment]
В плане испытаний все гуд, думаю тикет пока можно поставить на паузу. 
Нужны испытания.

**Comment by DronCode** [comment]
Написать unit тесты
- [ ] JUST DO IT

**Comment by DronCode** [comment]
Тесты добавлены

**Comment by kpa6uu** [comment]
Опасность
